---
apiVersion: v1
kind: Service
metadata:
  name: the-Wild-service
  namespace: thewildoasis
spec:
  selector:
    app: The-Wild-Oasis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
